from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                 Table, TableStyle, HRFlowable)
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from datetime import datetime

def generate_pdf_report(username: str, health_data: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm,
                             leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("title", parent=styles["Title"],
                                  fontSize=22, textColor=colors.HexColor("#1e40af"),
                                  spaceAfter=6, alignment=TA_CENTER)
    sub_style = ParagraphStyle("sub", parent=styles["Normal"],
                                fontSize=11, textColor=colors.grey,
                                alignment=TA_CENTER, spaceAfter=4)
    h2_style = ParagraphStyle("h2", parent=styles["Heading2"],
                               fontSize=14,
                               textColor=colors.HexColor("#1e40af"),
                               spaceBefore=14, spaceAfter=6)
    body_style = styles["Normal"]

    # Title
    story.append(Paragraph("HealthTwin AI", title_style))
    story.append(Paragraph("Personalised Health Risk Report", sub_style))
    story.append(Paragraph(
        f"Generated for: <b>{username}</b> &nbsp;|&nbsp; "
        f"{datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')}",
        sub_style))
    story.append(HRFlowable(width="100%", thickness=1,
                             color=colors.HexColor("#1e40af")))
    story.append(Spacer(1, 0.4*cm))

    # Health Score
    score = health_data.get("health_score", {})
    total = score.get("total", score) if isinstance(score, dict) else score
    breakdown = score.get("breakdown", {}) if isinstance(score, dict) else {}

    story.append(Paragraph("Health Score Summary", h2_style))
    score_color = ("#16a34a" if total >= 75 else
                   "#d97706" if total >= 50 else "#dc2626")
    story.append(Paragraph(
        f'Overall Health Score: <font color="{score_color}"><b>{total} / 100</b></font>',
        body_style))
    story.append(Spacer(1, 0.3*cm))

    if breakdown:
        bd_data = [["Pillar", "Score", "Max"]] + [
            [k.title(), str(v), "25"] for k, v in breakdown.items()
        ]
        bd_table = Table(bd_data, colWidths=[6*cm, 3*cm, 3*cm])
        bd_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1e40af")),
            ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
            ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0,1), (-1,-1),
             [colors.whitesmoke, colors.white]),
            ("GRID", (0,0), (-1,-1), 0.5, colors.lightgrey),
            ("ALIGN", (1,0), (-1,-1), "CENTER"),
        ]))
        story.append(bd_table)

    story.append(Spacer(1, 0.4*cm))
    story.append(Paragraph("Disease Risk Predictions", h2_style))

    # Risk table
    predictions = health_data.get("predictions", [])
    LABELS = {
        "diabetes": "Type 2 Diabetes", "hypertension": "Hypertension",
        "heart": "Heart Disease", "obesity": "Obesity", "stress": "Stress"
    }
    risk_data = [["Condition", "Risk Level", "Probability", "Top Factor"]]
    for p in predictions:
        top_feat = (p["top_shap_features"][0]["feature"]
                    if p.get("top_shap_features") else "—")
        risk_data.append([
            LABELS.get(p["condition"], p["condition"]),
            p["risk_level"],
            f"{p['risk_probability']*100:.1f}%",
            top_feat
        ])

    risk_table = Table(risk_data,
                       colWidths=[5*cm, 3*cm, 3*cm, 6*cm])
    risk_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1e40af")),
        ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
        ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0,1), (-1,-1),
         [colors.whitesmoke, colors.white]),
        ("GRID", (0,0), (-1,-1), 0.5, colors.lightgrey),
        ("ALIGN", (1,0), (-1,-1), "CENTER"),
    ]))
    story.append(risk_table)
    story.append(Spacer(1, 0.4*cm))

    # Disclaimer
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=colors.lightgrey))
    story.append(Spacer(1, 0.25*cm))
    disclaimer = ParagraphStyle("disc", parent=styles["Normal"],
                                 fontSize=8, textColor=colors.grey)
    story.append(Paragraph(
        "Disclaimer: This report is generated by an AI system for "
        "informational purposes only and does not constitute medical "
        "advice. Please consult a qualified healthcare professional "
        "for diagnosis and treatment decisions.",
        disclaimer))

    doc.build(story)
    return buffer.getvalue()
